CREATE MATERIALIZED VIEW LOG ON Customers

CREATE MATERIALIZED VIEW LOG ON Customers WITH PRIMARY KEY, ROWID;

CREATE MATERIALIZED VIEW LOG ON sales 
   WITH ROWID, SEQUENCE(amount_sold, time_id, prod_id)
   INCLUDNG NEW VALUES;
